GET http://localhost:8080/student/find?id=7

###
POST http://localhost:8080/student
Content-Type: application/json

{
  "name": "test",
  "age": 99
}

###
GET http://localhost:8080/student/7/faculty

###
DELETE http://localhost:8080/student/20

###
GET http://localhost:8080/student/count

###
GET http://localhost:8080/student/averageAge

###
GET http://localhost:8080/student/lastStudents?number=1

###
POST http://localhost:8080/faculty
Content-Type: application/json

{
  "name": "test",
  "color": "test"
}

###
DELETE http://localhost:8080/faculty/7

###
POST http://localhost:8080/avatar/9
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="avatar"; filename="bellatrix.jpg"
Content-Type: image/jpeg

<./avatar.jpg
--WebAppBoundary
